config/routes.rb
Houndapp::Application.routes.draw do
  root to: 'home#index'

  get '/auth/github/callback', to: 'sessions#create'
  get '/sign_in', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  get '/configuration', to: 'application#configuration'

  resources :builds, only: [:create]
  resources :repos, only: [:index] do
    resource :activation, only: [:create]
    resource :deactivation, only: [:create]
  end
  resources :repo_syncs, only: [:index, :create]
end

app/views/shared/_footer.haml
%footer.app-footer
  %p
    Hound is maintained by #{link_to 'thoughtbot', 'http://thoughtbot.com'}.
    Questions? Tweet #{link_to '@houndci', 'https://twitter.com/houndci'}.

  %p
    Hound is Copyright &copy; #{Date.today.year} thoughtbot. It is free software, and may be
    redistributed under the terms specified in the #{link_to 'LICENSE', 'https://github.com/thoughtbot/hound/blob/master/LICENSE'} file.

  .links
    = link_to 'Github', 'https://github.com/thoughtbot/hound', class: 'button'

app/views/shared/_header.haml
%header
  %h1.logo Hound
  - if signed_in?
    %ul
      %li
        %span
          = current_user

      - unless current_page?(configuration_path)
        %li
          = link_to 'Configuration', configuration_path

      - unless current_page?(root_path)
        %li
          = link_to 'Your Repos', root_path

      %li
        = link_to 'Sign Out', sign_out_path

app/views/shared/_intercom_settings.haml
:javascript
  analytics.identify("#{current_user.id}", {
    created : "#{current_user.created_at}",
    username : "#{current_user.github_username}"
  }, {
    Intercom : {
      userHash : "#{OpenSSL::HMAC.hexdigest('sha256', ENV['INTERCOM_API_SECRET'], current_user.id.to_s)}"
    }
  });

app/views/shared/_segment_io.haml
:javascript
  window.analytics||(window.analytics=[]),window.analytics.methods=["identify","track","trackLink","trackForm","trackClick","trackSubmit","page","pageview","ab","alias","ready","group","on","once","off"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var method=window.analytics.methods[i];window.analytics[method]=window.analytics.factory(method)}window.analytics.load=function(t){var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)},window.analytics.SNIPPET_VERSION="2.0.8",
  window.analytics.load("#{ENV['SEGMENT_IO_WRITE_KEY']}");
  window.analytics.page();

- if signed_in?
  = render 'shared/intercom_settings'